### PR TITLE
More natural usage of the as_initial_layer argument

### PR DESCRIPTION
**Pull request by nithishdivakar**

### CODE REVIEW

**Comment by wuaalb** [comment]
I don't completely understand why `as_initial_layer=False` is more natural than `True` (I assume this is for some DBN type usage?). For me a RBM class working like an isolated RBM is more natural.

Regarding the PR; could you make the implementation symmetric between BB-RBM and GB-RBM (i.e. both test for positive condition)? While you're at it, the first `if  as_initial_layer:` has doubled white space.

**Comment by nithishdivakar** [comment]
ITs more natural as usually the layer is used during sampling and we might have to add many(20+) layers to do that. In all those cases, only one of them is initial layer. In this case i can do
get_xx_layer(as_initial_layer=True)
get_xx_layer()
...
...
get_xx_layer()

In the previous case it would be 
get_xx_layer()
get_xx_layer(as_initial_layer=False)
...
...
get_xx_layer(as_initial_layer=False)


Code gets more cluttered in this.

**Comment by nithishdivakar** [comment]
Added Deep Belief Networks

**Comment by wuaalb** [comment]
Thanks!

Sorry, I don't have time to review this right now...
But, will merge anyways :)

**Pull request merged**
